server:
  port: 8080
  servlet:
    context-path: /li-test
spring:
  application:
    name: li-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dev:3306/drools?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 50
      max-wait-millis: 1000